window.WEDDING_MANAGER_DATA = {
  "baseUrl": "https://fgreco1984.github.io/wedding-invitation/invito-20260704.html",
  "generatedAt": "2026-06-20T09:00:36.039Z",
  "guests": [
    {
      "row": 2,
      "number": 1,
      "side": "Fabio",
      "name": "Lucrezia",
      "surname": "Salerno",
      "fullName": "Lucrezia Salerno",
      "relation": "Madre",
      "brindisi": "Sì",
      "companions": 1,
      "phone": "393290073425",
      "email": "",
      "table": "",
      "notes": "",
      "id": "F001",
      "language": "Italiano",
      "inviteLink": "index.html?id=F001&name=Lucrezia+Salerno&lang=it",
      "sendStatus": "Da inviare",
      "sentDate": "",
      "rsvpStatus": "In attesa",
      "rsvpDate": "=IF(C2=\"\",\"\",IFERROR(LOOKUP(2,1/((RSVP_Risposte!$C$2:$C$300=L2)*(RSVP_Risposte!$L$2:$L$300=\"OK\")),RSVP_Risposte!$A$2:$A$300),IFERROR(LOOKUP(2,1/(RSVP_Risposte!$D$2:$D$300=M2),RSVP_Risposte!$A$2:$A$300),\"\")))",
      "hasChildren": false,
      "travelsFromAway": false,
      "companionTypes": {
        "husband": true,
        "wife": false,
        "child1": false,
        "child2": false,
        "child3": false
      },
      "phoneCountry": "it",
      "hotelNights": {
        "before": false,
        "wedding": false,
        "after": false
      },
      "needsAccommodation": false,
      "_key": "guest-mqf7bhan-0-f06z82",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false
    },
    {
      "row": 4,
      "number": 2,
      "side": "Fabio",
      "name": "Antonio",
      "surname": "Greco",
      "fullName": "Antonio Greco",
      "relation": "Fratello",
      "brindisi": "Sì",
      "companions": 2,
      "phone": "393476925063",
      "email": "",
      "table": "",
      "notes": "",
      "id": "F003",
      "language": "Italiano",
      "inviteLink": "index.html?id=F003&name=Antonio+Greco&lang=it",
      "sendStatus": "Da inviare",
      "sentDate": "",
      "rsvpStatus": "In attesa",
      "rsvpDate": "=IF(C4=\"\",\"\",IFERROR(LOOKUP(2,1/((RSVP_Risposte!$C$2:$C$300=L4)*(RSVP_Risposte!$L$2:$L$300=\"OK\")),RSVP_Risposte!$A$2:$A$300),IFERROR(LOOKUP(2,1/(RSVP_Risposte!$D$2:$D$300=M4),RSVP_Risposte!$A$2:$A$300),\"\")))",
      "hasChildren": false,
      "travelsFromAway": false,
      "companionTypes": {
        "husband": false,
        "wife": true,
        "child1": true,
        "child2": false,
        "child3": false
      },
      "phoneCountry": "it",
      "hotelNights": {
        "before": false,
        "wedding": false,
        "after": false
      },
      "needsAccommodation": false,
      "_key": "guest-mqf7bhao-1-nzniv3",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false
    },
    {
      "row": 5,
      "number": 3,
      "side": "Inna",
      "name": "Vladymir",
      "surname": "Korolchuck",
      "fullName": "Vladymir Korolchuck",
      "relation": "Suocero",
      "brindisi": "No",
      "companions": 1,
      "phone": "34696679924",
      "email": "",
      "table": "",
      "notes": "",
      "id": "I004",
      "language": "Українська",
      "inviteLink": "index.html?id=I004&name=Vladymir+Korolchuck&lang=ua&travel=1&hotel=1",
      "sendStatus": "Da inviare",
      "sentDate": "",
      "rsvpStatus": "In attesa",
      "rsvpDate": "=IF(C5=\"\",\"\",IFERROR(LOOKUP(2,1/((RSVP_Risposte!$C$2:$C$300=L5)*(RSVP_Risposte!$L$2:$L$300=\"OK\")),RSVP_Risposte!$A$2:$A$300),IFERROR(LOOKUP(2,1/(RSVP_Risposte!$D$2:$D$300=M5),RSVP_Risposte!$A$2:$A$300),\"\")))",
      "hasChildren": false,
      "travelsFromAway": true,
      "companionTypes": {
        "husband": false,
        "wife": true,
        "child1": false,
        "child2": false,
        "child3": false
      },
      "phoneCountry": "es",
      "hotelNights": {
        "before": true,
        "wedding": true,
        "after": true
      },
      "needsAccommodation": true,
      "_key": "guest-mqf7bhao-2-ldwieu",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false
    },
    {
      "row": 7,
      "number": 4,
      "side": "Fabio",
      "name": "Concetta",
      "surname": "Roma",
      "fullName": "Concetta Roma",
      "relation": "Conoscente",
      "brindisi": "Sì",
      "companions": 0,
      "phone": "",
      "email": "",
      "table": "",
      "notes": "",
      "id": "F006",
      "language": "Italiano",
      "inviteLink": "index.html?id=F006&name=Concetta+Roma&lang=it",
      "sendStatus": "Da inviare",
      "sentDate": "",
      "rsvpStatus": "In attesa",
      "rsvpDate": "=IF(C7=\"\",\"\",IFERROR(LOOKUP(2,1/((RSVP_Risposte!$C$2:$C$300=L7)*(RSVP_Risposte!$L$2:$L$300=\"OK\")),RSVP_Risposte!$A$2:$A$300),IFERROR(LOOKUP(2,1/(RSVP_Risposte!$D$2:$D$300=M7),RSVP_Risposte!$A$2:$A$300),\"\")))",
      "hasChildren": false,
      "travelsFromAway": false,
      "companionTypes": {
        "husband": false,
        "wife": false,
        "child1": false,
        "child2": false,
        "child3": false
      },
      "hotelNights": {
        "before": false,
        "wedding": false,
        "after": false
      },
      "needsAccommodation": false,
      "_key": "guest-mqf7bhao-3-kd6hse",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false
    },
    {
      "row": 8,
      "number": 5,
      "side": "Fabio",
      "name": "Roberto",
      "surname": "Calabretti",
      "fullName": "Roberto Calabretti",
      "relation": "Amico",
      "brindisi": "Sì",
      "companions": 1,
      "phone": "393496533356",
      "email": "",
      "table": "",
      "notes": "",
      "id": "F007",
      "language": "Italiano",
      "inviteLink": "index.html?id=F007&name=Roberto+Calabretti&lang=it&kids=1",
      "sendStatus": "Da inviare",
      "sentDate": "",
      "rsvpStatus": "In attesa",
      "rsvpDate": "=IF(C8=\"\",\"\",IFERROR(LOOKUP(2,1/((RSVP_Risposte!$C$2:$C$300=L8)*(RSVP_Risposte!$L$2:$L$300=\"OK\")),RSVP_Risposte!$A$2:$A$300),IFERROR(LOOKUP(2,1/(RSVP_Risposte!$D$2:$D$300=M8),RSVP_Risposte!$A$2:$A$300),\"\")))",
      "hasChildren": true,
      "travelsFromAway": false,
      "companionTypes": {
        "husband": false,
        "wife": true,
        "child1": false,
        "child2": false,
        "child3": false
      },
      "phoneCountry": "it",
      "hotelNights": {
        "before": false,
        "wedding": false,
        "after": false
      },
      "needsAccommodation": false,
      "_key": "guest-mqf7bhao-4-3v3pro",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false
    },
    {
      "row": 9,
      "number": 6,
      "side": "Fabio",
      "name": "Marco",
      "surname": "Vecchi",
      "fullName": "Marco Vecchi",
      "relation": "Cugino",
      "brindisi": "No",
      "companions": 2,
      "phone": "393927918108",
      "email": "",
      "table": "",
      "notes": "",
      "id": "F008",
      "language": "Italiano",
      "inviteLink": "index.html?id=F008&name=Marco+Vecchi&lang=it&travel=1&hotel=1",
      "sendStatus": "Da inviare",
      "sentDate": "",
      "rsvpStatus": "In attesa",
      "rsvpDate": "=IF(C9=\"\",\"\",IFERROR(LOOKUP(2,1/((RSVP_Risposte!$C$2:$C$300=L9)*(RSVP_Risposte!$L$2:$L$300=\"OK\")),RSVP_Risposte!$A$2:$A$300),IFERROR(LOOKUP(2,1/(RSVP_Risposte!$D$2:$D$300=M9),RSVP_Risposte!$A$2:$A$300),\"\")))",
      "hasChildren": false,
      "travelsFromAway": true,
      "companionTypes": {
        "husband": false,
        "wife": true,
        "child1": true,
        "child2": false,
        "child3": false
      },
      "phoneCountry": "it",
      "hotelNights": {
        "before": true,
        "wedding": true,
        "after": false
      },
      "needsAccommodation": true,
      "_key": "guest-mqf7bhao-5-fd7tgw",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false
    },
    {
      "row": 10,
      "number": 7,
      "side": "Fabio",
      "name": "Davide",
      "surname": "Vecchi",
      "fullName": "Davide Vecchi",
      "relation": "Cugino",
      "brindisi": "No",
      "companions": 0,
      "phone": "393272698388",
      "email": "",
      "table": "",
      "notes": "",
      "id": "F009",
      "language": "Italiano",
      "inviteLink": "index.html?id=F009&name=Davide+Vecchi&lang=it&kids=1&travel=1&hotel=1",
      "sendStatus": "Da inviare",
      "sentDate": "",
      "rsvpStatus": "In attesa",
      "rsvpDate": "=IF(C10=\"\",\"\",IFERROR(LOOKUP(2,1/((RSVP_Risposte!$C$2:$C$300=L10)*(RSVP_Risposte!$L$2:$L$300=\"OK\")),RSVP_Risposte!$A$2:$A$300),IFERROR(LOOKUP(2,1/(RSVP_Risposte!$D$2:$D$300=M10),RSVP_Risposte!$A$2:$A$300),\"\")))",
      "hasChildren": true,
      "travelsFromAway": true,
      "companionTypes": {
        "husband": false,
        "wife": false,
        "child1": false,
        "child2": false,
        "child3": false
      },
      "phoneCountry": "it",
      "hotelNights": {
        "before": true,
        "wedding": true,
        "after": false
      },
      "needsAccommodation": true,
      "_key": "guest-mqf7bhao-6-igkssg",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false
    },
    {
      "row": 11,
      "number": 8,
      "side": "Fabio",
      "name": "Domenica",
      "surname": "Salerno",
      "fullName": "Domenica Salerno",
      "relation": "Zia",
      "brindisi": "No",
      "companions": 0,
      "phone": "",
      "email": "",
      "table": "",
      "notes": "",
      "id": "F010",
      "language": "Italiano",
      "inviteLink": "index.html?id=F010&name=Domenica+Salerno&lang=it",
      "sendStatus": "Da inviare",
      "sentDate": "",
      "rsvpStatus": "In attesa",
      "rsvpDate": "=IF(C11=\"\",\"\",IFERROR(LOOKUP(2,1/((RSVP_Risposte!$C$2:$C$300=L11)*(RSVP_Risposte!$L$2:$L$300=\"OK\")),RSVP_Risposte!$A$2:$A$300),IFERROR(LOOKUP(2,1/(RSVP_Risposte!$D$2:$D$300=M11),RSVP_Risposte!$A$2:$A$300),\"\")))",
      "hasChildren": false,
      "travelsFromAway": false,
      "companionTypes": {
        "husband": false,
        "wife": false,
        "child1": false,
        "child2": false,
        "child3": false
      },
      "phoneCountry": "it",
      "hotelNights": {
        "before": false,
        "wedding": false,
        "after": false
      },
      "needsAccommodation": false,
      "_key": "guest-mqf7bhao-7-ys7hn3",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false
    },
    {
      "row": 12,
      "number": 9,
      "side": "Fabio",
      "name": "Alexandra",
      "surname": "Salerno",
      "fullName": "Alexandra Salerno",
      "relation": "Cugina",
      "brindisi": "No",
      "companions": 1,
      "phone": "393299832276",
      "email": "",
      "table": "",
      "notes": "",
      "id": "F011",
      "language": "Italiano",
      "inviteLink": "index.html?id=F011&name=Alexandra+Salerno&lang=it",
      "sendStatus": "Da inviare",
      "sentDate": "",
      "rsvpStatus": "In attesa",
      "rsvpDate": "=IF(C12=\"\",\"\",IFERROR(LOOKUP(2,1/((RSVP_Risposte!$C$2:$C$300=L12)*(RSVP_Risposte!$L$2:$L$300=\"OK\")),RSVP_Risposte!$A$2:$A$300),IFERROR(LOOKUP(2,1/(RSVP_Risposte!$D$2:$D$300=M12),RSVP_Risposte!$A$2:$A$300),\"\")))",
      "hasChildren": false,
      "travelsFromAway": false,
      "companionTypes": {
        "husband": true,
        "wife": false,
        "child1": false,
        "child2": false,
        "child3": false
      },
      "phoneCountry": "it",
      "hotelNights": {
        "before": false,
        "wedding": false,
        "after": false
      },
      "needsAccommodation": false,
      "_key": "guest-mqf7bhao-8-s93paw",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false
    },
    {
      "row": 13,
      "number": 10,
      "side": "Fabio",
      "name": "Joseph",
      "surname": "Salerno",
      "fullName": "Joseph Salerno",
      "relation": "Cugino",
      "brindisi": "No",
      "companions": 0,
      "phone": "13122847137",
      "email": "",
      "table": "",
      "notes": "",
      "id": "F012",
      "language": "English",
      "inviteLink": "index.html?id=F012&name=Joseph+Salerno&lang=en",
      "sendStatus": "Da inviare",
      "sentDate": "",
      "rsvpStatus": "In attesa",
      "rsvpDate": "=IF(C13=\"\",\"\",IFERROR(LOOKUP(2,1/((RSVP_Risposte!$C$2:$C$300=L13)*(RSVP_Risposte!$L$2:$L$300=\"OK\")),RSVP_Risposte!$A$2:$A$300),IFERROR(LOOKUP(2,1/(RSVP_Risposte!$D$2:$D$300=M13),RSVP_Risposte!$A$2:$A$300),\"\")))",
      "hasChildren": false,
      "travelsFromAway": false,
      "companionTypes": {
        "husband": false,
        "wife": false,
        "child1": false,
        "child2": false,
        "child3": false
      },
      "phoneCountry": "us",
      "hotelNights": {
        "before": false,
        "wedding": false,
        "after": false
      },
      "needsAccommodation": false,
      "_key": "guest-mqf7bhao-9-3f1rc4",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false
    },
    {
      "row": 14,
      "number": 11,
      "side": "Fabio",
      "name": "Salvatore",
      "surname": "Salerno",
      "fullName": "Salvatore Salerno",
      "relation": "Zio",
      "brindisi": "No",
      "companions": 0,
      "phone": "16304617439",
      "email": "",
      "table": "",
      "notes": "",
      "id": "F013",
      "language": "Italiano",
      "inviteLink": "index.html?id=F013&name=Salvatore+Salerno&lang=it",
      "sendStatus": "Da inviare",
      "sentDate": "",
      "rsvpStatus": "In attesa",
      "rsvpDate": "=IF(C14=\"\",\"\",IFERROR(LOOKUP(2,1/((RSVP_Risposte!$C$2:$C$300=L14)*(RSVP_Risposte!$L$2:$L$300=\"OK\")),RSVP_Risposte!$A$2:$A$300),IFERROR(LOOKUP(2,1/(RSVP_Risposte!$D$2:$D$300=M14),RSVP_Risposte!$A$2:$A$300),\"\")))",
      "hasChildren": false,
      "travelsFromAway": false,
      "companionTypes": {
        "husband": false,
        "wife": false,
        "child1": false,
        "child2": false,
        "child3": false
      },
      "phoneCountry": "us",
      "hotelNights": {
        "before": false,
        "wedding": false,
        "after": false
      },
      "needsAccommodation": false,
      "_key": "guest-mqf7bhao-10-fadoce",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false
    },
    {
      "row": 15,
      "number": 12,
      "side": "Fabio",
      "name": "Andrea",
      "surname": "Salerno",
      "fullName": "Andrea Salerno",
      "relation": "Zio",
      "brindisi": "No",
      "companions": 0,
      "phone": "17087691347",
      "email": "",
      "table": "",
      "notes": "",
      "id": "F014",
      "language": "Italiano",
      "inviteLink": "index.html?id=F014&name=Andrea+Salerno&lang=it",
      "sendStatus": "Da inviare",
      "sentDate": "",
      "rsvpStatus": "In attesa",
      "rsvpDate": "=IF(C15=\"\",\"\",IFERROR(LOOKUP(2,1/((RSVP_Risposte!$C$2:$C$300=L15)*(RSVP_Risposte!$L$2:$L$300=\"OK\")),RSVP_Risposte!$A$2:$A$300),IFERROR(LOOKUP(2,1/(RSVP_Risposte!$D$2:$D$300=M15),RSVP_Risposte!$A$2:$A$300),\"\")))",
      "hasChildren": false,
      "travelsFromAway": false,
      "companionTypes": {
        "husband": false,
        "wife": false,
        "child1": false,
        "child2": false,
        "child3": false
      },
      "phoneCountry": "us",
      "hotelNights": {
        "before": false,
        "wedding": false,
        "after": false
      },
      "needsAccommodation": false,
      "_key": "guest-mqf7bhao-11-q08fh4",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false
    },
    {
      "row": 16,
      "number": 13,
      "side": "Fabio",
      "name": "Giuseppe",
      "surname": "Salerno",
      "fullName": "Giuseppe Salerno",
      "relation": "Cugino",
      "brindisi": "No",
      "companions": 0,
      "phone": "393383169661",
      "email": "",
      "table": "",
      "notes": "",
      "id": "F015",
      "language": "Italiano",
      "inviteLink": "index.html?id=F015&name=Giuseppe+Salerno&lang=it&travel=1&hotel=1",
      "sendStatus": "Da inviare",
      "sentDate": "",
      "rsvpStatus": "In attesa",
      "rsvpDate": "=IF(C16=\"\",\"\",IFERROR(LOOKUP(2,1/((RSVP_Risposte!$C$2:$C$300=L16)*(RSVP_Risposte!$L$2:$L$300=\"OK\")),RSVP_Risposte!$A$2:$A$300),IFERROR(LOOKUP(2,1/(RSVP_Risposte!$D$2:$D$300=M16),RSVP_Risposte!$A$2:$A$300),\"\")))",
      "hasChildren": false,
      "travelsFromAway": true,
      "companionTypes": {
        "husband": false,
        "wife": false,
        "child1": false,
        "child2": false,
        "child3": false
      },
      "phoneCountry": "it",
      "hotelNights": {
        "before": true,
        "wedding": true,
        "after": false
      },
      "needsAccommodation": true,
      "_key": "guest-mqf7bhao-12-lx3bw6",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false
    },
    {
      "row": 17,
      "number": 14,
      "side": "Fabio",
      "name": "Francesca",
      "surname": "Giannone",
      "fullName": "Francesca Giannone",
      "relation": "Amica",
      "brindisi": "Sì",
      "companions": 1,
      "phone": "393423433082",
      "email": "",
      "table": "",
      "notes": "",
      "id": "F016",
      "language": "Italiano",
      "inviteLink": "index.html?id=F016&name=Francesca+Giannone&lang=it",
      "sendStatus": "Da inviare",
      "sentDate": "",
      "rsvpStatus": "In attesa",
      "rsvpDate": "=IF(C17=\"\",\"\",IFERROR(LOOKUP(2,1/((RSVP_Risposte!$C$2:$C$300=L17)*(RSVP_Risposte!$L$2:$L$300=\"OK\")),RSVP_Risposte!$A$2:$A$300),IFERROR(LOOKUP(2,1/(RSVP_Risposte!$D$2:$D$300=M17),RSVP_Risposte!$A$2:$A$300),\"\")))",
      "hasChildren": false,
      "travelsFromAway": false,
      "companionTypes": {
        "husband": true,
        "wife": false,
        "child1": false,
        "child2": false,
        "child3": false
      },
      "phoneCountry": "it",
      "hotelNights": {
        "before": false,
        "wedding": false,
        "after": false
      },
      "needsAccommodation": false,
      "_key": "guest-mqf7bhao-13-nbmjfz",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false
    },
    {
      "row": 18,
      "number": 15,
      "side": "Fabio",
      "name": "Valentina",
      "surname": "Campanella",
      "fullName": "Valentina Campanella",
      "relation": "Amica",
      "brindisi": "Sì",
      "companions": 0,
      "phone": "393801972080",
      "email": "",
      "table": "",
      "notes": "",
      "id": "F017",
      "language": "Italiano",
      "inviteLink": "index.html?id=F017&name=Valentina+Campanella&lang=it",
      "sendStatus": "Da inviare",
      "sentDate": "",
      "rsvpStatus": "In attesa",
      "rsvpDate": "=IF(C18=\"\",\"\",IFERROR(LOOKUP(2,1/((RSVP_Risposte!$C$2:$C$300=L18)*(RSVP_Risposte!$L$2:$L$300=\"OK\")),RSVP_Risposte!$A$2:$A$300),IFERROR(LOOKUP(2,1/(RSVP_Risposte!$D$2:$D$300=M18),RSVP_Risposte!$A$2:$A$300),\"\")))",
      "hasChildren": false,
      "travelsFromAway": false,
      "companionTypes": {
        "husband": false,
        "wife": false,
        "child1": false,
        "child2": false,
        "child3": false
      },
      "phoneCountry": "it",
      "hotelNights": {
        "before": false,
        "wedding": false,
        "after": false
      },
      "needsAccommodation": false,
      "_key": "guest-mqf7bhao-14-aw7w5l",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false
    },
    {
      "row": 19,
      "number": 16,
      "side": "Fabio",
      "name": "Paolo",
      "surname": "Sarli",
      "fullName": "Paolo Sarli",
      "relation": "Amico/a di Fabio",
      "brindisi": "Sì",
      "companions": 1,
      "phone": "393371615016",
      "email": "",
      "table": "",
      "notes": "",
      "id": "F018",
      "language": "Italiano",
      "inviteLink": "index.html?id=F018&name=Paolo+Sarli&lang=it&kids=1",
      "sendStatus": "Da inviare",
      "sentDate": "",
      "rsvpStatus": "In attesa",
      "rsvpDate": "=IF(C19=\"\",\"\",IFERROR(LOOKUP(2,1/((RSVP_Risposte!$C$2:$C$300=L19)*(RSVP_Risposte!$L$2:$L$300=\"OK\")),RSVP_Risposte!$A$2:$A$300),IFERROR(LOOKUP(2,1/(RSVP_Risposte!$D$2:$D$300=M19),RSVP_Risposte!$A$2:$A$300),\"\")))",
      "hasChildren": true,
      "travelsFromAway": false,
      "companionTypes": {
        "husband": true,
        "wife": false,
        "child1": false,
        "child2": false,
        "child3": false
      },
      "phoneCountry": "it",
      "hotelNights": {
        "before": false,
        "wedding": false,
        "after": false
      },
      "needsAccommodation": false,
      "_key": "guest-mqf7bhao-15-gyz41m",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false
    },
    {
      "row": 20,
      "number": 17,
      "side": "Fabio",
      "name": "Giuseppe",
      "surname": "Giannoccaro",
      "fullName": "Giuseppe Giannoccaro",
      "relation": "Ex collega",
      "brindisi": "Sì",
      "companions": 0,
      "phone": "393356729917",
      "email": "",
      "table": "",
      "notes": "",
      "id": "F019",
      "language": "Italiano",
      "inviteLink": "index.html?id=F019&name=Giuseppe+Giannoccaro&lang=it",
      "sendStatus": "Da inviare",
      "sentDate": "",
      "rsvpStatus": "In attesa",
      "rsvpDate": "=IF(C20=\"\",\"\",IFERROR(LOOKUP(2,1/((RSVP_Risposte!$C$2:$C$300=L20)*(RSVP_Risposte!$L$2:$L$300=\"OK\")),RSVP_Risposte!$A$2:$A$300),IFERROR(LOOKUP(2,1/(RSVP_Risposte!$D$2:$D$300=M20),RSVP_Risposte!$A$2:$A$300),\"\")))",
      "hasChildren": false,
      "travelsFromAway": false,
      "companionTypes": {
        "husband": false,
        "wife": false,
        "child1": false,
        "child2": false,
        "child3": false
      },
      "phoneCountry": "it",
      "hotelNights": {
        "before": false,
        "wedding": false,
        "after": false
      },
      "needsAccommodation": false,
      "_key": "guest-mqf7bhao-16-d03tei",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false
    },
    {
      "row": 21,
      "number": 18,
      "side": "Fabio",
      "name": "Antonio",
      "surname": "Nuzzi",
      "fullName": "Antonio Nuzzi",
      "relation": "Compare",
      "brindisi": "Sì",
      "companions": 1,
      "phone": "393394960167",
      "email": "",
      "table": "",
      "notes": "",
      "id": "F020",
      "language": "Italiano",
      "inviteLink": "index.html?id=F020&name=Antonio+Nuzzi&lang=it&kids=1",
      "sendStatus": "Da inviare",
      "sentDate": "",
      "rsvpStatus": "In attesa",
      "rsvpDate": "=IF(C21=\"\",\"\",IFERROR(LOOKUP(2,1/((RSVP_Risposte!$C$2:$C$300=L21)*(RSVP_Risposte!$L$2:$L$300=\"OK\")),RSVP_Risposte!$A$2:$A$300),IFERROR(LOOKUP(2,1/(RSVP_Risposte!$D$2:$D$300=M21),RSVP_Risposte!$A$2:$A$300),\"\")))",
      "hasChildren": true,
      "travelsFromAway": false,
      "companionTypes": {
        "husband": false,
        "wife": true,
        "child1": false,
        "child2": false,
        "child3": false
      },
      "phoneCountry": "it",
      "hotelNights": {
        "before": false,
        "wedding": false,
        "after": false
      },
      "needsAccommodation": false,
      "_key": "guest-mqf7bhao-17-ujc6kf",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false
    },
    {
      "row": 22,
      "number": 19,
      "side": "Fabio",
      "name": "Silvia",
      "surname": "De Paola",
      "fullName": "Silvia De Paola",
      "relation": "Amico/a di Fabio",
      "brindisi": "Sì",
      "companions": 1,
      "phone": "393203521492",
      "email": "",
      "table": "",
      "notes": "",
      "id": "F021",
      "language": "Italiano",
      "inviteLink": "index.html?id=F021&name=Silvia+De+Paola&lang=it&kids=1",
      "sendStatus": "Da inviare",
      "sentDate": "",
      "rsvpStatus": "In attesa",
      "rsvpDate": "=IF(C22=\"\",\"\",IFERROR(LOOKUP(2,1/((RSVP_Risposte!$C$2:$C$300=L22)*(RSVP_Risposte!$L$2:$L$300=\"OK\")),RSVP_Risposte!$A$2:$A$300),IFERROR(LOOKUP(2,1/(RSVP_Risposte!$D$2:$D$300=M22),RSVP_Risposte!$A$2:$A$300),\"\")))",
      "hasChildren": true,
      "travelsFromAway": false,
      "companionTypes": {
        "husband": true,
        "wife": false,
        "child1": false,
        "child2": false,
        "child3": false
      },
      "phoneCountry": "it",
      "hotelNights": {
        "before": false,
        "wedding": false,
        "after": false
      },
      "needsAccommodation": false,
      "_key": "guest-mqf7bhao-18-95r2gz",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false
    },
    {
      "row": 23,
      "number": 20,
      "side": "Fabio",
      "name": "Lucia",
      "surname": "Rubino",
      "fullName": "Lucia Rubino",
      "relation": "Amico/a di Fabio",
      "brindisi": "Sì",
      "companions": 0,
      "phone": "41798893517",
      "email": "",
      "table": "",
      "notes": "",
      "id": "F022",
      "language": "Italiano",
      "inviteLink": "index.html?id=F022&name=Lucia+Rubino&lang=it",
      "sendStatus": "Da inviare",
      "sentDate": "",
      "rsvpStatus": "In attesa",
      "rsvpDate": "=IF(C23=\"\",\"\",IFERROR(LOOKUP(2,1/((RSVP_Risposte!$C$2:$C$300=L23)*(RSVP_Risposte!$L$2:$L$300=\"OK\")),RSVP_Risposte!$A$2:$A$300),IFERROR(LOOKUP(2,1/(RSVP_Risposte!$D$2:$D$300=M23),RSVP_Risposte!$A$2:$A$300),\"\")))",
      "hasChildren": false,
      "travelsFromAway": false,
      "companionTypes": {
        "husband": false,
        "wife": false,
        "child1": false,
        "child2": false,
        "child3": false
      },
      "phoneCountry": "ch",
      "hotelNights": {
        "before": false,
        "wedding": false,
        "after": false
      },
      "needsAccommodation": false,
      "_key": "guest-mqf7bhao-19-qntbde",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false
    },
    {
      "row": 24,
      "number": 21,
      "side": "Fabio",
      "name": "Angelo",
      "surname": "Semeraro",
      "fullName": "Angelo Semeraro",
      "relation": "Amico/a di Fabio",
      "brindisi": "Sì",
      "companions": 1,
      "phone": "447976981313",
      "email": "",
      "table": "",
      "notes": "",
      "id": "F023",
      "language": "Italiano",
      "inviteLink": "index.html?id=F023&name=Angelo+Semeraro&lang=it",
      "sendStatus": "Da inviare",
      "sentDate": "",
      "rsvpStatus": "In attesa",
      "rsvpDate": "=IF(C24=\"\",\"\",IFERROR(LOOKUP(2,1/((RSVP_Risposte!$C$2:$C$300=L24)*(RSVP_Risposte!$L$2:$L$300=\"OK\")),RSVP_Risposte!$A$2:$A$300),IFERROR(LOOKUP(2,1/(RSVP_Risposte!$D$2:$D$300=M24),RSVP_Risposte!$A$2:$A$300),\"\")))",
      "hasChildren": false,
      "travelsFromAway": false,
      "companionTypes": {
        "husband": false,
        "wife": true,
        "child1": false,
        "child2": false,
        "child3": false
      },
      "phoneCountry": "gb",
      "hotelNights": {
        "before": false,
        "wedding": false,
        "after": false
      },
      "needsAccommodation": false,
      "_key": "guest-mqf7bhao-20-71eobw",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false
    },
    {
      "row": 25,
      "number": 22,
      "side": "Fabio",
      "name": "Francesco",
      "surname": "Simone",
      "fullName": "Francesco Simone",
      "relation": "Amico/a di Fabio",
      "brindisi": "Sì",
      "companions": 1,
      "phone": "393491421816",
      "email": "",
      "table": "",
      "notes": "",
      "id": "F024",
      "language": "Italiano",
      "inviteLink": "index.html?id=F024&name=Francesco+Simone&lang=it&kids=1",
      "sendStatus": "Da inviare",
      "sentDate": "",
      "rsvpStatus": "In attesa",
      "rsvpDate": "=IF(C25=\"\",\"\",IFERROR(LOOKUP(2,1/((RSVP_Risposte!$C$2:$C$300=L25)*(RSVP_Risposte!$L$2:$L$300=\"OK\")),RSVP_Risposte!$A$2:$A$300),IFERROR(LOOKUP(2,1/(RSVP_Risposte!$D$2:$D$300=M25),RSVP_Risposte!$A$2:$A$300),\"\")))",
      "hasChildren": true,
      "travelsFromAway": false,
      "companionTypes": {
        "husband": false,
        "wife": true,
        "child1": false,
        "child2": false,
        "child3": false
      },
      "phoneCountry": "it",
      "hotelNights": {
        "before": false,
        "wedding": false,
        "after": false
      },
      "needsAccommodation": false,
      "_key": "guest-mqf7bhao-21-euan4q",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false
    },
    {
      "row": 26,
      "number": 23,
      "side": "Entrambi",
      "name": "Georges",
      "surname": "Bouj",
      "fullName": "Georges Bouj",
      "relation": "Amico/a degli sposi",
      "brindisi": "No",
      "companions": 1,
      "phone": "96899788672",
      "email": "",
      "table": "",
      "notes": "",
      "id": "I025",
      "language": "English",
      "inviteLink": "index.html?id=I025&name=Georges+Bouj&lang=en&kids=1&travel=1&hotel=1",
      "sendStatus": "Da inviare",
      "sentDate": "",
      "rsvpStatus": "In attesa",
      "rsvpDate": "=IF(C26=\"\",\"\",IFERROR(LOOKUP(2,1/((RSVP_Risposte!$C$2:$C$300=L26)*(RSVP_Risposte!$L$2:$L$300=\"OK\")),RSVP_Risposte!$A$2:$A$300),IFERROR(LOOKUP(2,1/(RSVP_Risposte!$D$2:$D$300=M26),RSVP_Risposte!$A$2:$A$300),\"\")))",
      "hasChildren": true,
      "travelsFromAway": true,
      "companionTypes": {
        "husband": false,
        "wife": true,
        "child1": false,
        "child2": false,
        "child3": false
      },
      "phoneCountry": "om",
      "hotelNights": {
        "before": true,
        "wedding": true,
        "after": true
      },
      "needsAccommodation": true,
      "_key": "guest-mqf7bhao-22-waw735",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false
    },
    {
      "row": 27,
      "number": 24,
      "side": "Entrambi",
      "name": "Natalie",
      "surname": "Piskova",
      "fullName": "Natalie Piskova",
      "relation": "Amico/a degli sposi",
      "brindisi": "No",
      "companions": 1,
      "phone": "447845915276",
      "email": "",
      "table": "",
      "notes": "",
      "id": "I026",
      "language": "English",
      "inviteLink": "index.html?id=I026&name=Natalie+Piskova&lang=en&travel=1&hotel=1",
      "sendStatus": "Da inviare",
      "sentDate": "",
      "rsvpStatus": "In attesa",
      "rsvpDate": "=IF(C27=\"\",\"\",IFERROR(LOOKUP(2,1/((RSVP_Risposte!$C$2:$C$300=L27)*(RSVP_Risposte!$L$2:$L$300=\"OK\")),RSVP_Risposte!$A$2:$A$300),IFERROR(LOOKUP(2,1/(RSVP_Risposte!$D$2:$D$300=M27),RSVP_Risposte!$A$2:$A$300),\"\")))",
      "hasChildren": false,
      "travelsFromAway": true,
      "companionTypes": {
        "husband": true,
        "wife": false,
        "child1": false,
        "child2": false,
        "child3": false
      },
      "phoneCountry": "gb",
      "hotelNights": {
        "before": true,
        "wedding": true,
        "after": true
      },
      "needsAccommodation": true,
      "_key": "guest-mqf7bhao-23-5niek0",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false
    },
    {
      "row": 28,
      "number": 25,
      "side": "Inna",
      "name": "Monica",
      "surname": "Dye",
      "fullName": "Monica Dye",
      "relation": "Amico/a di Inna",
      "brindisi": "No",
      "companions": 1,
      "phone": "447300365840",
      "email": "",
      "table": "",
      "notes": "",
      "id": "I027",
      "language": "English",
      "inviteLink": "index.html?id=I027&name=Monica+Dye&lang=en&kids=1&travel=1&hotel=1",
      "sendStatus": "Da inviare",
      "sentDate": "",
      "rsvpStatus": "In attesa",
      "rsvpDate": "=IF(C28=\"\",\"\",IFERROR(LOOKUP(2,1/((RSVP_Risposte!$C$2:$C$300=L28)*(RSVP_Risposte!$L$2:$L$300=\"OK\")),RSVP_Risposte!$A$2:$A$300),IFERROR(LOOKUP(2,1/(RSVP_Risposte!$D$2:$D$300=M28),RSVP_Risposte!$A$2:$A$300),\"\")))",
      "hasChildren": true,
      "travelsFromAway": true,
      "companionTypes": {
        "husband": true,
        "wife": false,
        "child1": false,
        "child2": false,
        "child3": false
      },
      "phoneCountry": "gb",
      "hotelNights": {
        "before": true,
        "wedding": true,
        "after": true
      },
      "needsAccommodation": true,
      "_key": "guest-mqf7bhao-24-0jz3qg",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false
    },
    {
      "row": 29,
      "number": 26,
      "side": "Inna",
      "name": "Inna",
      "surname": "Vudolob",
      "fullName": "Inna Vudolob",
      "relation": "Amico/a degli sposi",
      "brindisi": "No",
      "companions": 1,
      "phone": "971506343963",
      "email": "",
      "table": "",
      "notes": "",
      "id": "I028",
      "language": "Українська",
      "inviteLink": "index.html?id=I028&name=Inna+Vudolob&lang=ua&travel=1&hotel=1",
      "sendStatus": "Da inviare",
      "sentDate": "",
      "rsvpStatus": "In attesa",
      "rsvpDate": "=IF(C29=\"\",\"\",IFERROR(LOOKUP(2,1/((RSVP_Risposte!$C$2:$C$300=L29)*(RSVP_Risposte!$L$2:$L$300=\"OK\")),RSVP_Risposte!$A$2:$A$300),IFERROR(LOOKUP(2,1/(RSVP_Risposte!$D$2:$D$300=M29),RSVP_Risposte!$A$2:$A$300),\"\")))",
      "hasChildren": false,
      "travelsFromAway": true,
      "companionTypes": {
        "husband": true,
        "wife": false,
        "child1": false,
        "child2": false,
        "child3": false
      },
      "phoneCountry": "ae",
      "hotelNights": {
        "before": true,
        "wedding": true,
        "after": true
      },
      "needsAccommodation": true,
      "_key": "guest-mqf7bhao-25-fp9rhw",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false
    },
    {
      "row": 30,
      "number": 27,
      "side": "Entrambi",
      "name": "Sara",
      "surname": "Alkadury",
      "fullName": "Sara Alkadury",
      "relation": "Amico/a degli sposi",
      "brindisi": "No",
      "companions": 1,
      "phone": "96893888220",
      "email": "",
      "table": "",
      "notes": "",
      "id": "I029",
      "language": "English",
      "inviteLink": "index.html?id=I029&name=Sara+Alkadury&lang=en&kids=1&travel=1&hotel=1",
      "sendStatus": "Da inviare",
      "sentDate": "",
      "rsvpStatus": "In attesa",
      "rsvpDate": "=IF(C30=\"\",\"\",IFERROR(LOOKUP(2,1/((RSVP_Risposte!$C$2:$C$300=L30)*(RSVP_Risposte!$L$2:$L$300=\"OK\")),RSVP_Risposte!$A$2:$A$300),IFERROR(LOOKUP(2,1/(RSVP_Risposte!$D$2:$D$300=M30),RSVP_Risposte!$A$2:$A$300),\"\")))",
      "hasChildren": true,
      "travelsFromAway": true,
      "companionTypes": {
        "husband": true,
        "wife": false,
        "child1": false,
        "child2": false,
        "child3": false
      },
      "phoneCountry": "om",
      "hotelNights": {
        "before": true,
        "wedding": true,
        "after": true
      },
      "needsAccommodation": true,
      "_key": "guest-mqf7bhao-26-lzpv1e",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false
    },
    {
      "row": 31,
      "number": 28,
      "side": "Entrambi",
      "name": "Hussain",
      "surname": "Khaliq",
      "fullName": "Hussain Khaliq",
      "relation": "Amico/a di Inna",
      "brindisi": "No",
      "companions": 1,
      "phone": "96899388819",
      "email": "",
      "table": "",
      "notes": "",
      "id": "I030",
      "language": "English",
      "inviteLink": "index.html?id=I030&name=Hussain+Khaliq&lang=en&travel=1&hotel=1",
      "sendStatus": "Da inviare",
      "sentDate": "",
      "rsvpStatus": "In attesa",
      "rsvpDate": "=IF(C31=\"\",\"\",IFERROR(LOOKUP(2,1/((RSVP_Risposte!$C$2:$C$300=L31)*(RSVP_Risposte!$L$2:$L$300=\"OK\")),RSVP_Risposte!$A$2:$A$300),IFERROR(LOOKUP(2,1/(RSVP_Risposte!$D$2:$D$300=M31),RSVP_Risposte!$A$2:$A$300),\"\")))",
      "hasChildren": false,
      "travelsFromAway": true,
      "companionTypes": {
        "husband": false,
        "wife": true,
        "child1": false,
        "child2": false,
        "child3": false
      },
      "phoneCountry": "om",
      "hotelNights": {
        "before": true,
        "wedding": true,
        "after": true
      },
      "needsAccommodation": true,
      "_key": "guest-mqf7bhao-27-b1zvbw",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false
    },
    {
      "row": 32,
      "number": 29,
      "side": "Entrambi",
      "name": "Mahsa",
      "surname": "Maleki",
      "fullName": "Mahsa Maleki",
      "relation": "Amico/a degli sposi",
      "brindisi": "No",
      "companions": 0,
      "phone": "96879277716",
      "email": "",
      "table": "",
      "notes": "",
      "id": "I031",
      "language": "English",
      "inviteLink": "index.html?id=I031&name=Mahsa+Maleki&lang=en&travel=1&hotel=1",
      "sendStatus": "Da inviare",
      "sentDate": "",
      "rsvpStatus": "In attesa",
      "rsvpDate": "=IF(C32=\"\",\"\",IFERROR(LOOKUP(2,1/((RSVP_Risposte!$C$2:$C$300=L32)*(RSVP_Risposte!$L$2:$L$300=\"OK\")),RSVP_Risposte!$A$2:$A$300),IFERROR(LOOKUP(2,1/(RSVP_Risposte!$D$2:$D$300=M32),RSVP_Risposte!$A$2:$A$300),\"\")))",
      "hasChildren": false,
      "travelsFromAway": true,
      "companionTypes": {
        "husband": false,
        "wife": false,
        "child1": false,
        "child2": false,
        "child3": false
      },
      "phoneCountry": "om",
      "hotelNights": {
        "before": true,
        "wedding": true,
        "after": true
      },
      "needsAccommodation": true,
      "_key": "guest-mqf7bhao-28-zzk6y1",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false
    },
    {
      "row": 33,
      "number": 30,
      "side": "Inna",
      "name": "Marina",
      "surname": "Bonder",
      "fullName": "Marina Bonder",
      "relation": "Amico/a di Inna",
      "brindisi": "No",
      "companions": 0,
      "phone": "96898838092",
      "email": "",
      "table": "",
      "notes": "",
      "id": "I032",
      "language": "Українська",
      "inviteLink": "index.html?id=I032&name=Marina+Bonder&lang=ua&travel=1&hotel=1",
      "sendStatus": "Da inviare",
      "sentDate": "",
      "rsvpStatus": "In attesa",
      "rsvpDate": "=IF(C33=\"\",\"\",IFERROR(LOOKUP(2,1/((RSVP_Risposte!$C$2:$C$300=L33)*(RSVP_Risposte!$L$2:$L$300=\"OK\")),RSVP_Risposte!$A$2:$A$300),IFERROR(LOOKUP(2,1/(RSVP_Risposte!$D$2:$D$300=M33),RSVP_Risposte!$A$2:$A$300),\"\")))",
      "hasChildren": false,
      "travelsFromAway": true,
      "companionTypes": {
        "husband": false,
        "wife": false,
        "child1": false,
        "child2": false,
        "child3": false
      },
      "phoneCountry": "om",
      "hotelNights": {
        "before": true,
        "wedding": true,
        "after": true
      },
      "needsAccommodation": true,
      "_key": "guest-mqf7bhao-29-uto5tq",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false
    },
    {
      "row": 34,
      "number": 31,
      "side": "Inna",
      "name": "Irena",
      "surname": "Mykytun",
      "fullName": "Irena Mykytun",
      "relation": "Amico/a di Inna",
      "brindisi": "No",
      "companions": 0,
      "phone": "380979993761",
      "email": "",
      "table": "",
      "notes": "",
      "id": "I033",
      "language": "Українська",
      "inviteLink": "index.html?id=I033&name=Irena+Mykytun&lang=ua&travel=1&hotel=1",
      "sendStatus": "Da inviare",
      "sentDate": "",
      "rsvpStatus": "In attesa",
      "rsvpDate": "=IF(C34=\"\",\"\",IFERROR(LOOKUP(2,1/((RSVP_Risposte!$C$2:$C$300=L34)*(RSVP_Risposte!$L$2:$L$300=\"OK\")),RSVP_Risposte!$A$2:$A$300),IFERROR(LOOKUP(2,1/(RSVP_Risposte!$D$2:$D$300=M34),RSVP_Risposte!$A$2:$A$300),\"\")))",
      "hasChildren": false,
      "travelsFromAway": true,
      "companionTypes": {
        "husband": false,
        "wife": false,
        "child1": false,
        "child2": false,
        "child3": false
      },
      "phoneCountry": "ua",
      "hotelNights": {
        "before": true,
        "wedding": true,
        "after": true
      },
      "needsAccommodation": true,
      "_key": "guest-mqf7bhao-30-o72emn",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false
    },
    {
      "row": 35,
      "number": 32,
      "side": "Inna",
      "name": "Yuriy",
      "surname": "Syrko",
      "fullName": "Yuriy Syrko",
      "relation": "Amico/a di Inna",
      "brindisi": "No",
      "companions": 3,
      "phone": "34685179818",
      "email": "",
      "table": "",
      "notes": "",
      "id": "I034",
      "language": "Українська",
      "inviteLink": "index.html?id=I034&name=Yuriy+Syrko&lang=ua&kids=1&travel=1&hotel=1",
      "sendStatus": "Da inviare",
      "sentDate": "",
      "rsvpStatus": "In attesa",
      "rsvpDate": "=IF(C35=\"\",\"\",IFERROR(LOOKUP(2,1/((RSVP_Risposte!$C$2:$C$300=L35)*(RSVP_Risposte!$L$2:$L$300=\"OK\")),RSVP_Risposte!$A$2:$A$300),IFERROR(LOOKUP(2,1/(RSVP_Risposte!$D$2:$D$300=M35),RSVP_Risposte!$A$2:$A$300),\"\")))",
      "hasChildren": true,
      "travelsFromAway": true,
      "companionTypes": {
        "husband": true,
        "wife": true,
        "child1": true,
        "child2": false,
        "child3": false
      },
      "phoneCountry": "es",
      "hotelNights": {
        "before": true,
        "wedding": true,
        "after": true
      },
      "needsAccommodation": true,
      "_key": "guest-mqf7bhao-31-zy297f",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false
    },
    {
      "row": 36,
      "number": 33,
      "side": "Inna",
      "name": "Tanya",
      "surname": "Leo",
      "fullName": "Tanya Leo",
      "relation": "Comare",
      "brindisi": "No",
      "companions": 3,
      "phone": "491757127370",
      "email": "",
      "table": "",
      "notes": "",
      "id": "I035",
      "language": "Українська",
      "inviteLink": "index.html?id=I035&name=Tanya+Leo&lang=ua&kids=1&travel=1&hotel=1",
      "sendStatus": "Da inviare",
      "sentDate": "",
      "rsvpStatus": "In attesa",
      "rsvpDate": "=IF(C36=\"\",\"\",IFERROR(LOOKUP(2,1/((RSVP_Risposte!$C$2:$C$300=L36)*(RSVP_Risposte!$L$2:$L$300=\"OK\")),RSVP_Risposte!$A$2:$A$300),IFERROR(LOOKUP(2,1/(RSVP_Risposte!$D$2:$D$300=M36),RSVP_Risposte!$A$2:$A$300),\"\")))",
      "hasChildren": true,
      "travelsFromAway": true,
      "companionTypes": {
        "husband": true,
        "wife": false,
        "child1": true,
        "child2": true,
        "child3": false
      },
      "phoneCountry": "de",
      "hotelNights": {
        "before": true,
        "wedding": true,
        "after": true
      },
      "needsAccommodation": true,
      "_key": "guest-mqf7bhao-32-i5a3ux",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false
    },
    {
      "row": 37,
      "number": 34,
      "side": "Entrambi",
      "name": "Anyuta",
      "surname": "Gnatenko",
      "fullName": "Anyuta Gnatenko",
      "relation": "Amico/a degli sposi",
      "brindisi": "No",
      "companions": 1,
      "phone": "96872177720",
      "email": "",
      "table": "",
      "notes": "",
      "id": "I036",
      "language": "English",
      "inviteLink": "index.html?id=I036&name=Anyuta+Gnatenko&lang=en&travel=1&hotel=1",
      "sendStatus": "Da inviare",
      "sentDate": "",
      "rsvpStatus": "In attesa",
      "rsvpDate": "=IF(C37=\"\",\"\",IFERROR(LOOKUP(2,1/((RSVP_Risposte!$C$2:$C$300=L37)*(RSVP_Risposte!$L$2:$L$300=\"OK\")),RSVP_Risposte!$A$2:$A$300),IFERROR(LOOKUP(2,1/(RSVP_Risposte!$D$2:$D$300=M37),RSVP_Risposte!$A$2:$A$300),\"\")))",
      "hasChildren": false,
      "travelsFromAway": true,
      "companionTypes": {
        "husband": true,
        "wife": false,
        "child1": false,
        "child2": false,
        "child3": false
      },
      "phoneCountry": "om",
      "hotelNights": {
        "before": true,
        "wedding": true,
        "after": true
      },
      "needsAccommodation": true,
      "_key": "guest-mqf7bhao-33-bfzku9",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false
    },
    {
      "row": 38,
      "number": 35,
      "side": "Fabio",
      "name": "Mario",
      "surname": "Bertero",
      "fullName": "Mario Bertero",
      "relation": "Collega",
      "brindisi": "Si",
      "companions": 3,
      "phone": "96899330581",
      "email": "",
      "table": "",
      "notes": "",
      "id": "F037",
      "language": "Italiano",
      "inviteLink": "index.html?id=F037&name=Mario+Bertero&lang=it&kids=1",
      "sendStatus": "Da inviare",
      "sentDate": "",
      "rsvpStatus": "In attesa",
      "rsvpDate": "=IF(C38=\"\",\"\",IFERROR(LOOKUP(2,1/((RSVP_Risposte!$C$2:$C$300=L38)*(RSVP_Risposte!$L$2:$L$300=\"OK\")),RSVP_Risposte!$A$2:$A$300),IFERROR(LOOKUP(2,1/(RSVP_Risposte!$D$2:$D$300=M38),RSVP_Risposte!$A$2:$A$300),\"\")))",
      "hasChildren": true,
      "travelsFromAway": false,
      "companionTypes": {
        "husband": false,
        "wife": true,
        "child1": true,
        "child2": true,
        "child3": false
      },
      "phoneCountry": "om",
      "hotelNights": {
        "before": false,
        "wedding": false,
        "after": false
      },
      "needsAccommodation": false,
      "_key": "guest-mqf7bhao-34-h8kftj",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false
    },
    {
      "row": 39,
      "number": 36,
      "side": "Entrambi",
      "name": "Masha",
      "surname": "Brit",
      "fullName": "Masha Brit",
      "relation": "Amico/a degli sposi",
      "brindisi": "No",
      "companions": 0,
      "phone": "971524469453",
      "email": "",
      "table": "",
      "notes": "",
      "id": "F038",
      "language": "Italiano",
      "inviteLink": "index.html?id=F038&name=Masha+Brit&lang=it&travel=1&hotel=1",
      "sendStatus": "Da inviare",
      "sentDate": "",
      "rsvpStatus": "In attesa",
      "rsvpDate": "=IF(C39=\"\",\"\",IFERROR(LOOKUP(2,1/((RSVP_Risposte!$C$2:$C$300=L39)*(RSVP_Risposte!$L$2:$L$300=\"OK\")),RSVP_Risposte!$A$2:$A$300),IFERROR(LOOKUP(2,1/(RSVP_Risposte!$D$2:$D$300=M39),RSVP_Risposte!$A$2:$A$300),\"\")))",
      "hasChildren": false,
      "travelsFromAway": true,
      "companionTypes": {
        "husband": false,
        "wife": false,
        "child1": false,
        "child2": false,
        "child3": false
      },
      "phoneCountry": "ae",
      "hotelNights": {
        "before": true,
        "wedding": true,
        "after": true
      },
      "needsAccommodation": true,
      "_key": "guest-mqf7bhao-35-1p0le6",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false
    },
    {
      "row": 40,
      "number": 37,
      "side": "Fabio",
      "name": "Alexandra",
      "surname": "Madrid",
      "fullName": "Alexandra Madrid",
      "relation": "Amico/a degli sposi",
      "brindisi": "No",
      "companions": 0,
      "phone": "34641845915",
      "email": "",
      "table": "",
      "notes": "",
      "id": "F039",
      "language": "Italiano",
      "inviteLink": "index.html?id=F039&name=Alexandra+Madrid&lang=it&travel=1&hotel=1",
      "sendStatus": "Da inviare",
      "sentDate": "",
      "rsvpStatus": "In attesa",
      "rsvpDate": "=IF(C40=\"\",\"\",IFERROR(LOOKUP(2,1/((RSVP_Risposte!$C$2:$C$300=L40)*(RSVP_Risposte!$L$2:$L$300=\"OK\")),RSVP_Risposte!$A$2:$A$300),IFERROR(LOOKUP(2,1/(RSVP_Risposte!$D$2:$D$300=M40),RSVP_Risposte!$A$2:$A$300),\"\")))",
      "hasChildren": false,
      "travelsFromAway": true,
      "companionTypes": {
        "husband": false,
        "wife": false,
        "child1": false,
        "child2": false,
        "child3": false
      },
      "phoneCountry": "es",
      "hotelNights": {
        "before": true,
        "wedding": true,
        "after": true
      },
      "needsAccommodation": true,
      "_key": "guest-mqf7bhao-36-z0eobc",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false
    },
    {
      "row": 41,
      "number": 38,
      "side": "Fabio",
      "name": "Andrea",
      "surname": "Dell'Abate",
      "fullName": "Andrea Dell'Abate",
      "relation": "Collega",
      "brindisi": "Sì",
      "companions": 1,
      "phone": "393285811474",
      "email": "",
      "table": "",
      "notes": "",
      "id": "F040",
      "language": "Italiano",
      "inviteLink": "index.html?id=F040&name=Andrea+Dell%27Abate&lang=it&kids=1",
      "sendStatus": "Da inviare",
      "sentDate": "",
      "rsvpStatus": "In attesa",
      "rsvpDate": "=IF(C41=\"\",\"\",IFERROR(LOOKUP(2,1/((RSVP_Risposte!$C$2:$C$300=L41)*(RSVP_Risposte!$L$2:$L$300=\"OK\")),RSVP_Risposte!$A$2:$A$300),IFERROR(LOOKUP(2,1/(RSVP_Risposte!$D$2:$D$300=M41),RSVP_Risposte!$A$2:$A$300),\"\")))",
      "hasChildren": true,
      "travelsFromAway": false,
      "companionTypes": {
        "husband": false,
        "wife": true,
        "child1": false,
        "child2": false,
        "child3": false
      },
      "phoneCountry": "it",
      "hotelNights": {
        "before": false,
        "wedding": false,
        "after": false
      },
      "needsAccommodation": false,
      "_key": "guest-mqf7bhao-37-y6k76g",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false
    },
    {
      "row": 42,
      "number": 39,
      "side": "Fabio",
      "name": "Giovanna",
      "surname": "Lamontagna",
      "fullName": "Giovanna Lamontagna",
      "relation": "Amico/a di Fabio",
      "brindisi": "No",
      "companions": 1,
      "phone": "393490518027",
      "email": "",
      "table": "",
      "notes": "",
      "id": "F041",
      "language": "Italiano",
      "inviteLink": "index.html?id=F041&name=Giovanna+Lamontagna&lang=it&kids=1&travel=1&hotel=1",
      "sendStatus": "Da inviare",
      "sentDate": "",
      "rsvpStatus": "In attesa",
      "rsvpDate": "=IF(C42=\"\",\"\",IFERROR(LOOKUP(2,1/((RSVP_Risposte!$C$2:$C$300=L42)*(RSVP_Risposte!$L$2:$L$300=\"OK\")),RSVP_Risposte!$A$2:$A$300),IFERROR(LOOKUP(2,1/(RSVP_Risposte!$D$2:$D$300=M42),RSVP_Risposte!$A$2:$A$300),\"\")))",
      "hasChildren": true,
      "travelsFromAway": true,
      "companionTypes": {
        "husband": true,
        "wife": false,
        "child1": false,
        "child2": false,
        "child3": false
      },
      "phoneCountry": "it",
      "hotelNights": {
        "before": false,
        "wedding": true,
        "after": false
      },
      "needsAccommodation": true,
      "_key": "guest-mqf7bhao-38-9j8cqu",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false
    },
    {
      "row": 43,
      "number": 40,
      "side": "Inna",
      "name": "Oxana",
      "surname": "Sidor",
      "fullName": "Oxana Sidor",
      "relation": "Amico/a di Inna",
      "brindisi": "No",
      "companions": 1,
      "phone": "380950090062",
      "email": "",
      "table": "",
      "notes": "",
      "id": "I042",
      "language": "Українська",
      "inviteLink": "index.html?id=I042&name=Oxana+Sidor&lang=ua&kids=1&travel=1&hotel=1",
      "sendStatus": "Da inviare",
      "sentDate": "",
      "rsvpStatus": "In attesa",
      "rsvpDate": "=IF(C43=\"\",\"\",IFERROR(LOOKUP(2,1/((RSVP_Risposte!$C$2:$C$300=L43)*(RSVP_Risposte!$L$2:$L$300=\"OK\")),RSVP_Risposte!$A$2:$A$300),IFERROR(LOOKUP(2,1/(RSVP_Risposte!$D$2:$D$300=M43),RSVP_Risposte!$A$2:$A$300),\"\")))",
      "hasChildren": true,
      "travelsFromAway": true,
      "companionTypes": {
        "husband": true,
        "wife": false,
        "child1": false,
        "child2": false,
        "child3": false
      },
      "phoneCountry": "ua",
      "hotelNights": {
        "before": true,
        "wedding": true,
        "after": true
      },
      "needsAccommodation": true,
      "_key": "guest-mqf7bhao-39-od9r4w",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false
    },
    {
      "id": "G042",
      "language": "Italiano",
      "side": "Fabio",
      "name": "Carlo",
      "surname": "Iurlaro",
      "relation": "Parente Fabio",
      "brindisi": "No",
      "companionTypes": {
        "husband": false,
        "wife": true,
        "child1": false,
        "child2": false,
        "child3": false
      },
      "companions": 1,
      "phone": "",
      "phoneCountry": "it",
      "email": "",
      "table": "",
      "notes": "",
      "sendStatus": "Da inviare",
      "rsvpStatus": "In attesa",
      "hasChildren": false,
      "travelsFromAway": false,
      "number": 41,
      "fullName": "Carlo Iurlaro",
      "inviteLink": "index.html?id=G042&name=Carlo+Iurlaro&lang=it",
      "hotelNights": {
        "before": false,
        "wedding": false,
        "after": false
      },
      "needsAccommodation": false,
      "_key": "guest-mqf7bhao-40-7p72ag",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false
    },
    {
      "id": "G043",
      "language": "English",
      "side": "Inna",
      "name": "Jose",
      "surname": "Villalobos",
      "relation": "Amico/a di Inna",
      "brindisi": "No",
      "companionTypes": {
        "husband": false,
        "wife": true,
        "child1": false,
        "child2": false,
        "child3": false
      },
      "companions": 1,
      "phone": "34687724989",
      "phoneCountry": "es",
      "email": "",
      "table": "",
      "notes": "",
      "sendStatus": "Da inviare",
      "rsvpStatus": "In attesa",
      "hasChildren": false,
      "travelsFromAway": true,
      "number": 42,
      "fullName": "Jose Villalobos",
      "inviteLink": "index.html?id=G043&name=Jose+Villalobos&lang=en&travel=1&hotel=1",
      "hotelNights": {
        "before": true,
        "wedding": true,
        "after": true
      },
      "needsAccommodation": true,
      "_key": "guest-mqf7bhao-41-mi4poc",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false
    },
    {
      "id": "G045",
      "language": "Italiano",
      "side": "Fabio",
      "name": "Michele",
      "surname": "Iurlaro",
      "relation": "Parente Fabio",
      "brindisi": "No",
      "companionTypes": {
        "husband": false,
        "wife": true,
        "child1": false,
        "child2": false,
        "child3": false
      },
      "companions": 1,
      "phone": "393471172629",
      "phoneCountry": "it",
      "email": "",
      "table": "",
      "notes": "",
      "sendStatus": "Da inviare",
      "rsvpStatus": "In attesa",
      "hasChildren": false,
      "travelsFromAway": false,
      "number": 43,
      "fullName": "Michele Iurlaro",
      "inviteLink": "index.html?id=G045&name=Michele+Iurlaro&lang=it",
      "hotelNights": {
        "before": false,
        "wedding": false,
        "after": false
      },
      "needsAccommodation": false,
      "_key": "guest-mqf7bhao-42-4t7sgq",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false
    },
    {
      "id": "G044",
      "language": "English",
      "side": "Entrambi",
      "name": "Bannia",
      "surname": "Bustamante",
      "relation": "Amico/a degli sposi",
      "brindisi": "No",
      "companionTypes": {
        "husband": true,
        "wife": false,
        "child1": false,
        "child2": false,
        "child3": false
      },
      "companions": 1,
      "phone": "971526196863",
      "phoneCountry": "ae",
      "email": "",
      "table": "",
      "notes": "",
      "sendStatus": "Da inviare",
      "rsvpStatus": "In attesa",
      "hasChildren": true,
      "travelsFromAway": true,
      "number": 44,
      "fullName": "Bannia Bustamante",
      "inviteLink": "index.html?id=G044&name=Bannia+Bustamante&lang=en&kids=1&travel=1&hotel=1",
      "hotelNights": {
        "before": true,
        "wedding": true,
        "after": true
      },
      "needsAccommodation": true,
      "_key": "guest-mqf7bhao-43-258jhp",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false
    },
    {
      "id": "G046",
      "language": "Italiano",
      "side": "Fabio",
      "name": "Maria Grazia",
      "surname": "Salerno",
      "relation": "Parente Fabio",
      "brindisi": "No",
      "companionTypes": {
        "husband": true,
        "wife": false,
        "child1": true,
        "child2": true,
        "child3": false
      },
      "companions": 3,
      "phone": "393345662059",
      "phoneCountry": "it",
      "email": "",
      "table": "",
      "notes": "",
      "sendStatus": "Da inviare",
      "rsvpStatus": "In attesa",
      "needsAccommodation": true,
      "hotelNights": {
        "before": true,
        "wedding": true,
        "after": false
      },
      "hasChildren": true,
      "travelsFromAway": true,
      "number": 45,
      "fullName": "Maria Grazia Salerno",
      "inviteLink": "index.html?id=G046&name=Maria+Grazia+Salerno&lang=it&kids=1&travel=1&hotel=1",
      "_key": "guest-mqf7bhap-45-iz4t81",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false
    },
    {
      "id": "G047",
      "language": "Italiano",
      "side": "Fabio",
      "name": "Vincenzo",
      "surname": "Galetta",
      "relation": "Amico/a di famiglia",
      "brindisi": "No",
      "companionTypes": {
        "husband": false,
        "wife": true,
        "child1": false,
        "child2": false,
        "child3": false
      },
      "companions": 1,
      "phone": "393339764052",
      "phoneCountry": "it",
      "email": "",
      "table": "",
      "notes": "",
      "sendStatus": "Da inviare",
      "rsvpStatus": "In attesa",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false,
      "needsAccommodation": false,
      "hotelNights": {
        "before": false,
        "wedding": false,
        "after": false
      },
      "hasChildren": false,
      "travelsFromAway": false,
      "_key": "guest-mql4tvuy-45-8uiuou",
      "number": 46,
      "fullName": "Vincenzo Galetta",
      "inviteLink": "index.html?id=G047&name=Vincenzo+Galetta&lang=it"
    },
    {
      "id": "G048",
      "language": "Italiano",
      "side": "Fabio",
      "name": "Lucia",
      "surname": "Greco",
      "relation": "Cugina",
      "brindisi": "No",
      "companionTypes": {
        "husband": true,
        "wife": false,
        "child1": false,
        "child2": false,
        "child3": false
      },
      "companions": 1,
      "phone": "393293555323",
      "phoneCountry": "it",
      "email": "",
      "table": "",
      "notes": "",
      "sendStatus": "Da inviare",
      "rsvpStatus": "In attesa",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false,
      "needsAccommodation": false,
      "hotelNights": {
        "before": false,
        "wedding": false,
        "after": false
      },
      "hasChildren": true,
      "travelsFromAway": false,
      "_key": "guest-mql4yxah-46-40jaa7",
      "number": 47,
      "fullName": "Lucia Greco",
      "inviteLink": "index.html?id=G048&name=Lucia+Greco&lang=it&kids=1"
    },
    {
      "id": "G049",
      "language": "Italiano",
      "side": "Fabio",
      "name": "Sara",
      "surname": "Greco",
      "relation": "Cugina",
      "brindisi": "No",
      "companionTypes": {
        "husband": true,
        "wife": false,
        "child1": false,
        "child2": false,
        "child3": false
      },
      "companions": 1,
      "phone": "393249066137",
      "phoneCountry": "it",
      "email": "",
      "table": "",
      "notes": "",
      "sendStatus": "Da inviare",
      "rsvpStatus": "In attesa",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false,
      "needsAccommodation": false,
      "hotelNights": {
        "before": false,
        "wedding": false,
        "after": false
      },
      "hasChildren": false,
      "travelsFromAway": false,
      "_key": "guest-mql52o1x-47-dtkb39",
      "number": 48,
      "fullName": "Sara Greco",
      "inviteLink": "index.html?id=G049&name=Sara+Greco&lang=it"
    },
    {
      "id": "G050",
      "language": "Italiano",
      "side": "Fabio",
      "name": "Giovanna",
      "surname": "Fiume",
      "relation": "Cugina",
      "brindisi": "No",
      "companionTypes": {
        "husband": true,
        "wife": false,
        "child1": false,
        "child2": false,
        "child3": false
      },
      "companions": 1,
      "phone": "393295035753",
      "phoneCountry": "it",
      "email": "",
      "table": "",
      "notes": "",
      "sendStatus": "Da inviare",
      "rsvpStatus": "In attesa",
      "saveDateSent": false,
      "saveDateViewed": false,
      "saveDateReplied": false,
      "saveDateFollowUp": false,
      "needsAccommodation": false,
      "hotelNights": {
        "before": false,
        "wedding": false,
        "after": false
      },
      "hasChildren": true,
      "travelsFromAway": false,
      "_key": "guest-mql54i6j-48-7ds4p4",
      "number": 49,
      "fullName": "Giovanna Fiume",
      "inviteLink": "index.html?id=G050&name=Giovanna+Fiume&lang=it&kids=1"
    }
  ],
  "hotelRooms": {
    "before": {
      "camera-1781524342592": [
        "guest-mqf7bhao-6-igkssg",
        "guest-mqf7bhao-12-lx3bw6"
      ],
      "camera-1781524350402": [
        "guest-mqf7bhao-29-uto5tq",
        "guest-mqf7bhao-30-o72emn"
      ],
      "camera-1781524352636": [
        "guest-mqf7bhao-35-1p0le6",
        "guest-mqf7bhao-36-z0eobc"
      ]
    },
    "wedding": {
      "camera-1781524355819": [
        "guest-mqf7bhao-6-igkssg",
        "guest-mqf7bhao-12-lx3bw6"
      ],
      "camera-1781524359053": [
        "guest-mqf7bhao-29-uto5tq",
        "guest-mqf7bhao-30-o72emn"
      ],
      "camera-1781524361169": [
        "guest-mqf7bhao-35-1p0le6",
        "guest-mqf7bhao-36-z0eobc"
      ]
    },
    "after": {
      "camera-1781524364069": [
        "guest-mqf7bhao-29-uto5tq",
        "guest-mqf7bhao-30-o72emn"
      ],
      "camera-1781524366302": [
        "guest-mqf7bhao-35-1p0le6",
        "guest-mqf7bhao-36-z0eobc"
      ]
    }
  },
  "weddingCosts": {
    "restaurantPerPax": 170,
    "restaurantDeposit": 0,
    "photographer": 0,
    "flowers": 0,
    "car": 0,
    "music": 0,
    "openBar": 0,
    "extraBuffet": 0,
    "preWeddingParty": 0,
    "bus": 0,
    "favors": 0,
    "fireworksLights": 0,
    "symbolicCeremony": 500,
    "siae": 0,
    "makeupHair": 0,
    "fabioOutfit": 0,
    "innaOutfit": 0,
    "unexpectedExtra": 0
  },
  "bankTransfers": {}
};
